services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    ports:
      - 3001:3001
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - ./data/anythingllm:/app/server/storage
      # - ./data/anythingllm/.env:/app/server/.env

  mlflow: # can be enhanced with separate db : https://medium.com/@hitorunajp/remote-mlflow-setup-with-docker-de54652241a4
    build:
      context: ./mlflow
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000
    volumes:
      - ./mlflow:/mlflow

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11435:11434"
    tty: true
    runtime: nvidia # https://docs.docker.com/desktop/features/gpu/
  
  agents-runner:
    build:
      context: .
      dockerfile: dev-agents.Dockerfile
    volumes:
      - ./src:/app
      - ./requirements.txt:/app/requirements.txt

volumes:
  ollama-data: