services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest
    ports:
      - 3001:3001
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - ./data/anythingllm:/app/server/storage
      # - ./data/anythingllm/.env:/app/server/.env

  mlflow: # can be enhanced with separate db : https://medium.com/@hitorunajp/remote-mlflow-setup-with-docker-de54652241a4
    build:
      context: ./mlflow
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000
    volumes:
      - ./mlflow:/mlflow

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11435:11434"
    tty: true
    runtime: nvidia # https://docs.docker.com/desktop/features/gpu/

  # db:
  #   image: postgres:15
  #   container_name: crewai_db
  #   env_file:
  #     - ./CrewAI-Studio/.env
  #   environment:
  #     POSTGRES_USER: crewai_user
  #     POSTGRES_PASSWORD: secret
  #     POSTGRES_DB: crewai
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # # The Streamlit app : https://github.com/strnad/CrewAI-Studio/tree/main
  # web:
  #   build: ./CrewAI-Studio
  #   container_name: crewai_studio
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./CrewAI-Studio/.env
  #   ports:
  #     - "8501:8501"

volumes:
  ollama-data:
  # db-data: